wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.15
    start_time: 1673279130.570595
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.15
      5: 0.13.7
      8:
      - 2
      - 3
      - 5
batch_size:
  desc: null
  value: 50
epochs:
  desc: null
  value: 10
hidden_dim:
  desc: null
  value: 400
latent_dim:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.001
